### ISSUE TITLE
Code release?

### ISSUE THREAD

**Issue by ZhangYang-UCAS** [HelenMao/MAG-Edit#1]
good work！！！
your project looks very interesting, do you have a date for it's release?

**Comment by HelenMao** [comment]
Thanks for your attention, we will release the codes soon, please stay stuned.

**Comment by zijinY** [comment]
Thanks for your fascinating work! Your model could be very helpful for my project, could you release the source code of the model first?

**Comment by CostaliyA** [comment]
> Thanks for your fascinating work! Your model could be very helpful for my project, could you release the source code of the model first?

I'm happy to tell you that we have released the code!
